# Site settings
title: The Porridge Box
email: spatte21@btinternet.com
description: > # this means to ignore newlines until "baseurl:"
  Nutritious and delicious, a healthy helping of blogging goodness.
  What better way to start the day?
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://spatterson.me.uk" # the base hostname & protocol for your site
twitter_username: spatte21
github_username:  spatte21

# Build settings
markdown: kramdown
